TMDB_API_KEY = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiIyMzc0ZmRjNTI3ZDM1MDc1ZDJhMTM3Mzc4ZTU0ODcwNSIsIm5iZiI6MTc3NDE5NDM2NC41MDgsInN1YiI6IjY5YzAwZWJjZTQ2M2Q4MTczZGEyNTJjMiIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.RcB8A_7feN5wEUAhoSw9r2cq9fQibhUWJtTg8dppfgk"

ANIME_LIST = [
    "Kaguya-sama wa Kokurasetai",
    "Seven Deadly Sins",
    "Fire Force",
    "Hokuto no Ken",
    "Tengen Toppa Gurren Lagann",
    "Black Butler",
    "Soul Eater",
    "The Promised Neverland",
    "Psycho-Pass",
    "Blue Exorcist",
    "Made in Abyss",
    "Overlord",
    "That Time I Got Reincarnated as a Slime",
    "Akame ga Kill!",
    "Kill la Kill",
    "Drifters",
    "Banana Fish",
    "Dororo",
    "Erased",
    "Fruits Basket",
    "Hellsing",
    "Baccano!",
    "Durarara!!",
    "Fate/Zero",
    "Fate/stay night",
    "Hell's Paradise",
    "Ranking of Kings",
    "Golden Kamuy",
    "The Rising of the Shield Hero",
    "Log Horizon",
    "No Game No Life",
    "Noragami",
    "D.Gray-man",
    "Beelzebub",
    "Katekyo Hitman Reborn!",
    "Trigun",
    "Samurai Champloo",
    "Yu-Gi-Oh!",
    "InuYasha",
    "Shaman King",
    "Nana",
    "Paranoia Agent",
    "Terror in Resonance",
    "March Comes in Like a Lion",
    "Given",
    "Horimiya",
    "Witch Hunter Robin",
    "Darker than Black",
    "Dorohedoro",
]
